image: maven:3.8.4-openjdk-17  # Use Maven 3.8.4 with Java 17

stages:
  - build

build:
  stage: build
  script:
    - java -version  # Print the Java version for verification
    - mvn -version  # Print the Maven version for verification
    - mvn clean install  # Use Maven to build your Java project
